### ISSUE TITLE
Google Generative AI

### ISSUE THREAD

**Issue by ohuc** [ITSpecialist111/ai_automation_suggester#13]
can we get a version which utilises google generative AI instead of OpenAI

**Comment by ITSpecialist111** [comment]
Love this! I am currently working on a drop-down menu that will allow you to choose the model you want, rather than defaulting to GPT-4o-mini. I initially encountered an issue with the configuration page that affected the functionality of the drop-down, but I will address this for you in the coming weeks. Additionally, I will add a new section for requests to the ReadMe file, which will include some proposed dates.

**Comment by ITSpecialist111** [comment]
V1.07 Now Provides these asks:

Removal of Automatic Scheduling:

Removed automatic scanning and suggestion generation due to complexities with triggering and user preferences.
Enhanced Stability: This change improves code stability and allows users to implement custom automation triggers that suit their individual needs.

Expanded AI Provider Support:

Added Support for Multiple LLM Models:
Google LLM Models: Now supports Google's AI models for generating automation suggestions.
Local AI Models: Introduced support for local models like LocalAI and Ollama for users who prefer privacy and do not rely on internet connectivity.

Custom LLM Variants:
Users can now choose custom AI model variants from higher models (e.g., OpenAI's o1-preview), providing more flexibility and control over the AI processing.
Enhanced Manual Trigger Service:

Integration Selection: Users can now select which AI provider integration to trigger when manually initiating the AI analysis.
Custom System Prompt: Allows users to override the built-in system prompt for more granular and personalized suggestions.
German Translation Added:

Global Reach: Introduced German language support to make the integration accessible to a wider audience.

**Comment by ohuc** [comment]
Amazing thanks for this great integration :)

**Comment by ohuc** [comment]
there seems to be an issue with the authentication, I tried using my google generative ai key which works perfectly with the in-built google generative AI integration however I get `Invalid authentication` error while trying to setup the integration
