### ISSUE TITLE
Rate limits configuration - Max tokens per day limiter and methods to split jobs to keep cost down?

### ISSUE THREAD

**Issue by Hedda** [ITSpecialist111/ai_automation_suggester#17]
Could a rate limits configuration be implemented to set max tokens per day limiter and method(s) to split jobs to keep cost down?

https://platform.openai.com/docs/guides/rate-limits

**Comment by ITSpecialist111** [comment]
V1.07 Now Provides these asks via manual service calls.

Removal of Automatic Scheduling:

Removed automatic scanning and suggestion generation due to complexities with triggering and user preferences.
Enhanced Stability: This change improves code stability and allows users to implement custom automation triggers that suit their individual needs.

Expanded AI Provider Support:

Added Support for Multiple LLM Models:
Google LLM Models: Now supports Google's AI models for generating automation suggestions.
Local AI Models: Introduced support for local models like LocalAI and Ollama for users who prefer privacy and do not rely on internet connectivity.

Custom LLM Variants:
Users can now choose custom AI model variants from higher models (e.g., OpenAI's o1-preview), providing more flexibility and control over the AI processing.
Enhanced Manual Trigger Service:

Integration Selection: Users can now select which AI provider integration to trigger when manually initiating the AI analysis.
Custom System Prompt: Allows users to override the built-in system prompt for more granular and personalized suggestions.
German Translation Added:

Global Reach: Introduced German language support to make the integration accessible to a wider audience.
