### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by ohuc** [ITSpecialist111/ai_automation_suggester#20]
there seems to be an issue with the authentication, I tried using my google generative ai key which works perfectly with the in-built google generative AI integration however I get `Invalid authentication` error while trying to setup the integration

**Comment by larschri15** [comment]
i got the same problem
butt cant find a solution

**Comment by friedpope** [comment]
Thought it was just me :).  Since this was my first attempt at running this, I rolled back to 1.06 and noticed that the whole API selection menu is new.  OpenAI works in 1.06 so I'm thinking there's just an issue with the authentication flows for 1.07 in these newly supported platforms.

**Comment by ghbaud** [comment]
Same problem

**Comment by DUC750** [comment]
The same with Anthropic. But OpenAI works flawlessly.

**Comment by Beast12** [comment]
Same here with Claude and Gemini

**Comment by ITSpecialist111** [comment]
**Thanks all - I can see the issue and have been running through the code to find the issue. There's a pending pull request for part of the issue for Google, of which I'm testing for the other providers mentioned above.

You can test this code by replacing the Config_flow.py file. (File can be found in the discussions tab in the Pull Requests above). Once we have this sorted I will release the bug fix.**

The root cause before the issue of unhelpful error messages was that the integration's code had incorrect implementation of the API key validation methods for some providers, specifically Google and Anthropic. This incorrect implementation led to the following problems:

Incorrect API Endpoints:

The validation functions were using outdated or incorrect API endpoints for Google and Anthropic.
For example, the endpoints used did not match the current API specifications provided by these services.
Incorrect Payloads and Headers:

The payloads sent in the API requests did not conform to the expected formats required by the APIs.
Headers necessary for authentication and versioning were missing or improperly formatted.
Incorrect HTTP Methods:

Some API calls were using the wrong HTTP method (e.g., using GET instead of POST or vice versa).
Lack of Model Specification:

The code did not correctly specify the models when making validation requests, or it used default models that the user might not have access to.
This could cause the API to reject the request due to an invalid or unauthorized model.

**Comment by stream74** [comment]
same groq, anthropic and gemini

**Comment by ITSpecialist111** [comment]
Updated to resolve issues within the code for authentication with other providers. *PLEASE* check the system logs if you receive API error messages, I will continue to work on a more suitable solution in the UI to look up error messages. 

Please update to V1.08:    https://github.com/ITSpecialist111/ai_automation_suggester/releases/tag/V1.08
