### ISSUE TITLE
Gemini AI authentication problem

### ISSUE THREAD

**Issue by atanas1054** [ITSpecialist111/ai_automation_suggester#27]
Hello,

Even after v1.08 I can't authenticate my API key with Gemini AI.

I can execute succesfully the curl command from 

https://aistudio.google.com/app/apikey 

therefore, the problem is not with my API key. When I enter the API key into the home assistant integration I get "API Error Occured"
Source: custom_components/ai_automation_suggester/config_flow.py:138

I tried different model names without any success too.

**Comment by atanas1054** [comment]
`Log details (ERROR)
This error originated from a custom integration.
Logger: custom_components.ai_automation_suggester.config_flow
Source: custom_components/ai_automation_suggester/config_flow.py:138
integration: AI Automation Suggester 
First occurred: November 3, 2024 at 7:51:22 PM (21 occurrences)
Last logged: 4:12:49 PM

Google validation error response:`

**Comment by ITSpecialist111** [comment]
Okay, thanks for this - this was working in the initial v1.08 - I will recheck.

Please bare with and I'll investigate.

**Comment by ITSpecialist111** [comment]
V1.1.0 now available to address this issue - please update.

key changes that fixed the Google API integration:

API Endpoint & Model Format:

Original error was due to incorrect model name format and API endpoint
The working curl command showed that the API expects:

Endpoint: .../v1beta/models/{model}:generateContent
Model format: gemini-1.5-pro (instead of the older format)




Request Structure:
jsonCopy{
  "contents": [
    {
      "parts": [
        {
          "text": "prompt here"
        }
      ]
    }
  ],
  "generationConfig": {
    "temperature": 0.7,
    "maxOutputTokens": 500,
    "topK": 40,
    "topP": 0.95
  }
}

This matches Google's Gemini API expectations
The original code was using a different structure meant for an older version


Response Parsing:
pythonCopyresult["candidates"][0]["content"]["parts"][0]["text"]

The response structure is different from other AI providers
We needed to navigate through the correct JSON path to get the generated text


Validation Method:

The validator now uses the same request structure as the main API call
This ensures consistent validation and actual usage
Both use :generateContent instead of the older :generateText


Generation Configuration:

Added proper Gemini-specific parameters:

maxOutputTokens instead of max_tokens
Added topK and topP parameters for better generation control
Proper temperature scaling
