### ISSUE TITLE
Scan_frequency not saved initially

### ISSUE THREAD

**Issue by tjorim** [ITSpecialist111/ai_automation_suggester#7]
Steps to reproduce:
1) set up integration with scan_frequency 0
2) click configure on the entry
3) see scan_frequency at the default 24
4) change it to 0 and submit again
5) click configure again
6) see scan_frequency is now correctly at 0

Version 1.06
Not sure if it's only a visual issue or an actual config bug.

**Comment by ITSpecialist111** [comment]
V1.07 Now Provides these asks:

Removal of Automatic Scheduling:

Removed automatic scanning and suggestion generation due to complexities with triggering and user preferences.
Enhanced Stability: This change improves code stability and allows users to implement custom automation triggers that suit their individual needs.

Expanded AI Provider Support:

Added Support for Multiple LLM Models:
Google LLM Models: Now supports Google's AI models for generating automation suggestions.
Local AI Models: Introduced support for local models like LocalAI and Ollama for users who prefer privacy and do not rely on internet connectivity.

Custom LLM Variants:
Users can now choose custom AI model variants from higher models (e.g., OpenAI's o1-preview), providing more flexibility and control over the AI processing.
Enhanced Manual Trigger Service:

Integration Selection: Users can now select which AI provider integration to trigger when manually initiating the AI analysis.
Custom System Prompt: Allows users to override the built-in system prompt for more granular and personalized suggestions.
German Translation Added:

Global Reach: Introduced German language support to make the integration accessible to a wider audience.

**Comment by ITSpecialist111** [comment]
Updated to resolve issues within tV1.08:  https://github.com/ITSpecialist111/ai_automation_suggester/releases/tag/V1.08
